---
- name: Configure nginx vhosts
  hosts: all
  become: yes

  vars:
    vhosts:
      - "etis.com"
      - "fizfak.ru"
      - "mehmat.ru"

  tasks:
    - name: Configure nginx virtual hosts
      include_role:
        name: nginx-vhosts
      loop: "{{ vhosts }}"
      loop_control:
        loop_var: vhost
